name: Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Generate lockfile
        run: uv lock

      - name: Install dependencies
        run: uv sync

      - name: Build EXE with PyInstaller
        run: uv run pyinstaller --onefile autosearch.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: autosearch
          path: dist/autosearch.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Tag: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Last commit message:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/autosearch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
